### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by seamustuohy** [sudomesh/luci-app-peopleswifi#8]
I have noticed you have removed the attribution and copyright notices of Steven and Jow from this code. I am curious why you have removed their attribution from code that the commit history shows is derived from their core work. I can't say I know the Apache License well enough to know how it handles source-code copyright and attribution, so I thought I would check in here..

**Comment by Juul** [comment]
You're right. It was removed because it seemed like the original code had been completely re-written (though looking back on it maybe some of the original is still left). Even so, the code is obviously derived from their work, so the copyright notices should stay, regardless of the license. Thanks for pointing this out, and thanks for the great work on Commotion!
